### ISSUE TITLE
tsc npm package

### ISSUE THREAD

**Issue by giang12** [ColonelBundy/moleculer-decorators#12]
![image](https://user-images.githubusercontent.com/5290460/54223398-a2f0c180-44b4-11e9-820f-6206da5c9db5.png)

Hi @ColonelBundy , I think you forgot to compile the package for couple of recent releases?

Nice work on this project btw, thanks for your contribution.

**Comment by davidfrtala** [comment]
Yep, the `/dist` folder is missing

**Comment by ColonelBundy** [comment]
Shoot... I knew I forgot something. Will be fixed asap!
