### ISSUE TITLE
Please respect the semver versioning scheme

### ISSUE THREAD

**Issue by giang12** [ColonelBundy/moleculer-decorators#14]
Hi @ColonelBundy this is not an bug issue but just wanna ask you to follow the right semver versioning scheme when releasing breaking changes, such as the recent merged PR from https://github.com/ColonelBundy/moleculer-decorators/pull/13. 

This PR created breaking change, released under patches 1.0.21 -> 1.0.22, causing our CI/CD process to fail....

Again thanks for the hard work on this module but respect the versioning scheme pls <3

**Comment by ColonelBundy** [comment]
@giang12 My bad, totally missed this. Will definitely check an extra time before releasing next time. Thanks!
