### ISSUE TITLE
noted the issue still exists. Heres the test repo https://github.com/giang12/moldecormixinsbug

### ISSUE THREAD

**Issue by giang12** [ColonelBundy/moleculer-decorators#17]
noted the issue still exists. Heres the test repo https://github.com/giang12/moldecormixinsbug

_Originally posted by @giang12 in https://github.com/ColonelBundy/moleculer-decorators/issues/15#issuecomment-486401046_

**Comment by davidfrtala** [comment]
I will fix it today!
