### ISSUE TITLE
moleculer-db lifecycle functions are excluded

### ISSUE THREAD

**Issue by davidfrtala** [ColonelBundy/moleculer-decorators#2]
I have a problem, with `moleculer-db` mixed into one of my services. `moleculer-db` contains lifecycle entity functions, that aren't actions, methods or events. They are global in the same way as `created()`, `started()` and `stopped()` functions. 

Namely
```
    afterConnected() {
        ...
    },

    entityCreated(json, ctx) {
        ...
    },

    entityUpdated(json, ctx) {
        ...
    },

    entityRemoved(json, ctx) {
        ...
    },  
```

And the problem is, that when I use db adapter, the moment when it connects to database, it's calling a function, which doesn't exists in the schema under `this.schema.afterConnected`

https://github.com/moleculerjs/moleculer-db/blob/b80c01bf1e4f6e4aae38f67b203bb58e428632b7/packages/moleculer-db/src/index.js#L389

and therefore, this service and its lifecycle db event won't trigger

```
@Service({
  name: "users",
  mixins: [DbService],
  adapter: new MongooseDbAdapter(process.env.MONGO_URI),
  model: UserModel
})
class UsersService extends BaseSchema {
  ...

  public async afterConnected() {
    const count = await this.adapter.count();
    if (count === 0) {
      await this.seedDB();
    } else {
      this.logger.info(`${count} users in DB. Skipping seed...`);
    }
  }
}
```

**Comment by ColonelBundy** [comment]
You need to use the ```@Method``` decorator if you need the function in the service, otherwize it's "private" and wont be accessible from a function that's been executed in the moleculer-context. 
In your case the ```afterConnected``` is being called from another moleculer service and in this case it's your mixin, that's why it's not accessible, unless you add the ```@Method``` decorator.
