### ISSUE TITLE
@Service() class-decorator implementation throws TypeError

### ISSUE THREAD

**Issue by ibox4real** [ColonelBundy/moleculer-decorators#20]
Reflect metadata throws an error when trying to use the @Service() decorator on a class

```ts
import { Service, Action } from 'moleculer-decorators';

@Service()
export default class DemoController {
    @Action({
        rest: 'GET /welcome',
    })
    welcome(ctx) {
        return 'Hello'
    }
}
```

`node_modules/reflect-metadata/Reflect.js`
```js
        function DecorateConstructor(decorators, target) {
            for (var i = decorators.length - 1; i >= 0; --i) {
                var decorator = decorators[i];
                var decorated = decorator(target);

                if (!IsUndefined(decorated) && !IsNull(decorated)) {
                    //Throws error because decorated is not a function but an object
                    if (!IsConstructor(decorated)) throw new TypeError();
                    target = decorated;
                }
            }
            return target;
        }
```

On closer inspection of decorator i see it returns an object. A class decorator should return nothing or a new function constructor.

```js

function (constructor) {
        let base = {
            name: ''
        };
        const _options = Object.assign({}, defaultServiceOptions, options);
        Object.defineProperty(base, 'name', {
            value: options.name || constructor.name,
            writable: false,
            enumerable: true
        });
        if (options.name) {
            delete options.name;
        }
        Object.assign(base, _.omit(options, Object.keys(defaultServiceOptions)));
        const parentService = constructor.prototype;
        const vars = [];
        Object.getOwnPropertyNames(parentService).forEach(function (key) {
            if (key === 'constructor') {
                if (_options.constructOverride) {
                    const ServiceClass = new parentService.constructor(mockServiceBroker);
                    Object.getOwnPropertyNames(ServiceClass).forEach(function (key) {
                        if (blacklist.indexOf(key) === -1 &&
                            !_.isFunction(ServiceClass[key])) {
                            base[key] = Object.getOwnPropertyDescriptor(ServiceClass, key).value;
                            if (blacklist2.indexOf(key) === -1) {
                                vars[key] = Object.getOwnPropertyDescriptor(ServiceClass, key).value;
                            }
                        }
                    });
                    const bypass = Object.defineProperty;
                    const obj = {};
                    bypass(obj, 'created', {
                        value: function created(broker) {
                            for (let key in vars) {
                                this[key] = vars[key];
                            }
                            if (Object.getOwnPropertyDescriptor(parentService, 'created') !=
                                null) {
                                Object.getOwnPropertyDescriptor(parentService, 'created').value.call(this, broker);
                            }
                        },
                        writable: true,
                        enumerable: true,
                        configurable: true
                    });
                    base['created'] = obj.created;
                }
                return;
            }
            const descriptor = Object.getOwnPropertyDescriptor(parentService, key);
            if (key === 'created' && !_options.constructOverride) {
                base[key] = descriptor.value;
            }
            if (key === 'started' || key === 'stopped') {
                base[key] = descriptor.value;
                return;
            }
            if (key === 'events' || key === 'methods' || key === 'actions') {
                base[key]
                    ? Object.assign(base[key], descriptor.value)
                    : (base[key] = descriptor.value);
                return;
            }
            if (key === 'afterConnected' ||
                key === 'entityCreated' ||
                key === 'entityUpdated' ||
                key === 'entityRemoved') {
                base[key] = descriptor.value;
                return;
            }
        });
        return base;
    }
```

**Comment by jalerg** [comment]
I am having the same issue, in my case the error is thrown when I add Sequelize (sequelize-typescript) anywhere in the service. I am not using sequelize as an adapter, business reasons behind that, instead I instantiate it directly and import the models from a shared project somewhere else in my monorepo. 

Remove sequelize from the service, it doesn't even go into reflect-metadata. 

Maybe this Service class decorator can be refactored to extend the class with a function that returns the `ServiceSchema` ? then use that function in `broker.createService()` instead? Not sure if this is possible at all, just wondering.

**Comment by jalerg** [comment]
follow up, I actually tested my theory and made it work. What I tested

1. in line 118 of `dist/index.js` I relaced `return base` with `return () => base;`
2. In my code I replaced `broker.createService(MyService);` with `broker.createService((MyService as any)());`

Had to do that `as any` to avoid typescript whining about not being able to invoke it. Pretty crappy I know. Now everything loads and I can keep going, but my unit tests are all dead, so not sure if this is worth it.. might just go back to plain classes with no decorators, at least I have the types.

**Comment by ColonelBundy** [comment]
@ibox4real 
You forgot ```extends moleculer.Service``` which might solve your issue. However,
The problem with returning a new constructor will inherently break mixins. Regarding it returning an object, this is a supported behavior since we transform our class into a standard object compatible with moleculer.

@jalerg 
The intended usage is to use ```broker.createService(MyService);```

Also, this library does not currently support the newer es6 class format that moleculer introduced in 0.13 since moleculer did not have classes when this library was created. There was an attempt to introduce support but it broke mixins as a result which I then rolled back.
The decorators are however still compatible with the older object-based format.

**Comment by ibox4real** [comment]
@ColonelBundy 
I don't think extending the `moleculer.Service` will help since the core issue here is that an object cannot be returned from a class-decorator. 

Btw you should take a look at (https://moleculer.services/docs/0.13/services.html). If i understood you correctly then those examples there are not supported.

The other issue is that this does not play well with other decorators like `typedi`;

I can implement other strategies to get around the issue, but maybe instead of directly returning a `ServiceSchema` gather metadata from the class via the decorators and then use that in a `ServiceSchemaFactory` to create the `ServiceSchema`.

Something like

```ts

import { Service, Action } from 'moleculer-decorators';

@Service({
    name: 'demo',
})
export default class DemoController {
    @Action({
        rest: 'GET /welcome',
    })
    welcome(ctx) {
        return 'Hello'
    }
}

```
```ts
import { getServiceMetadata } from 'moleculer-decorators'
class ServiceSchemaFactory {
    create(obj: Object) {
        const metadata = getServiceMetadata(obj.constructor.name);
        return this.buildServiceSchema(metadata,obj)
    }
    
   buildServiceSchema(metadata, obj) {
      return {
          name: metadata.name,
          actions: metadata.actions.reduce((actions, actionMetadata) => {
                actions[actionMetadata.name] = {
                        params: actionMetadata.params
                        handler: obj[actionMetadata.handlerFn]
                }
                return actions;
            },{})
      }
   }
}
```
 
```ts
const schemaFactory = new ServiceSchemaFactory();
const service = new DemoController;
const serviceSchema = schemaFactory.create(service);
...
broker.createService(serviceSchema);

```

**Comment by ColonelBundy** [comment]
@ibox4real 
The examples from moleculer do work though. The goal of this lib was to return a compatible schema and not a class since that was not supported at the time I created this. Sorry if I didn't make that clear.

If for compatibility sake and to play nice with other decorators, I'll accept any PR or test cases that will result in an easier time for any of you.


Consider this example:

```
import moleculer = require('moleculer');
import { Service, Action } from 'moleculer-decorators';
const broker = new moleculer.ServiceBroker({
  logLevel: 'debug'
});

@Service()
class ServiceName extends moleculer.Service {
  // With options
  // No need for "handler:{}" here
  @Action({
    cache: false,
    params: {
      a: 'number',
      b: 'number'
    },
    rest: 'GET /welcome'
  })
  test(ctx) {}
}

console.log(ServiceName);

broker.createService(ServiceName);
broker.start();
```

This example code returns a valid schema.

Output of the console.log:

```
{ name: 'ServiceName',
  created: [Function: created],
  actions:
   { test:
      { cache: false,
        params: [Object],
        rest: 'GET /welcome',
        handler: [Function: test] } } }
```

Which in turn can be used with ```broker.createService``` without using ``new``

So a decorator can, in fact, return an object.
I hope I understood you correctly.

**Comment by ibox4real** [comment]
@ColonelBundy 

yes, the schema returned is valid, but it does throw an error with reflect-metdata in typescript,

I just wanted to start a discussion if we can somehow make it compatible with reflect-metadata and other decorators.

**Comment by ColonelBundy** [comment]
@ibox4real Ah, yea we can fix this for sure. I'd welcome any pr if you already have a solution or get to it before I do. Thanks!

**Comment by jalerg** [comment]
I am taking a look at refactoring the Service decorator to use the `this.parseServiceSchema()` instead of just returning an object. Like suggested in the [ES6 moleculer docs](https://moleculer.services/docs/0.12/service.html#Native-ES6-classes-with-schema-parsing).

I'll raise a PR when/if I make it work well with the rest of the decorators in typescript.

**Comment by dobratu** [comment]
@jalerg Did you make it work?

**Comment by ujwal-setlur** [comment]
I am running in to this issue as well with packages that use reflect-metadata. Any progress on this @jalerg ?

**Comment by ColonelBundy** [comment]
Please try branch 1.2.0 and see if it works for you guys.

**Comment by ujwal-setlur** [comment]
This works for me now. Thanks! Can you please publish, and also add support for specifying schema for events that was added in moleculer-0.14?

**Comment by ColonelBundy** [comment]
@ujwal-setlur Good to hear, yes I will add support for that.
