### ISSUE TITLE
moleculer-0.14 support?

### ISSUE THREAD

**Issue by ujwal-setlur** [ColonelBundy/moleculer-decorators#22]
moleculer-0.14 is about to be released (it is at 0.14-rc1). Does this package need to be updated for the new version?

**Comment by ColonelBundy** [comment]
From a brief look at the changes, it looks like it should be useable. But I will definitely try the release candidates and update accordingly.

I'll keep this issue open until 0.14 has been released and moleculer-decorators have been verified and updated accordingly.

**Comment by ujwal-setlur** [comment]
Thanks! I have been using it and haven’t seen any issues yet, but just thought I would ask the question

**Comment by ujwal-setlur** [comment]
moleculer-0.14 has introduced schema declaration for events. Not sure if that is supported here

**Comment by lucduong** [comment]
@ujwal-setlur & @ColonelBundy should change from `Action` to `ActionSchema`.

**Comment by ColonelBundy** [comment]
Will take a look at this this week.

**Comment by ColonelBundy** [comment]
@ujwal-setlur @lucduong I have updated the branch "1.2.0" for support for 0.14, please try it out :)

**Comment by lucduong** [comment]
@ColonelBundy I can get it work well with personal changes same with you. Will test one more time, please consider to release soon

**Comment by ujwal-setlur** [comment]
I will test today as well. Code changes look correct. Would love to see a release soon

**Comment by ColonelBundy** [comment]
@ujwal-setlur @lucduong I will definitely release today after you guys have verified it works properly for you guys.

**Comment by ujwal-setlur** [comment]
@ColonelBundy  did a quick test, it works! Thanks!

**Comment by lucduong** [comment]
@ColonelBundy I got some errors:
```
Type 'ActionSchema' is not assignable to type 'boolean | ActionSchema | ActionHandler<any>'.
            Type 'ActionSchema' is not assignable to type 'true'.
```
and 
```
Type 'import("node_modules/moleculer/index").ServiceSchema<import("node_modules/moleculer/index").ServiceSettingSchema>' is not assignable to type 'import("node_modules/moleculer-decorators/node_modules/moleculer/index").ServiceSchema<import("node_modules/moleculer-decorators/node_modules/moleculer/index").ServiceSettingSchema>'
Types of property 'actions' are incompatible
```
I don't remember how I fixed in my forked

**Comment by lucduong** [comment]
@ColonelBundy Tried again and get it worked well. Thanks!

**Comment by ColonelBundy** [comment]
Great, will publish to npm today. Thanks!

**Comment by ColonelBundy** [comment]
Published.
