### ISSUE TITLE
Typeorm - reflect-metadata

### ISSUE THREAD

**Issue by damiandabrowski** [ColonelBundy/moleculer-decorators#3]
When i'm trying to use typeorm together with moleculer-decorators i throws an error decorating Service

TypeError in node_modules/reflect-metadata/Reflect.js:544:31

**Comment by ColonelBundy** [comment]
Could you provide me with more details on how to produce and/or sample code?

**Comment by damiandabrowski** [comment]
import {Action, Service} from 'moleculer-decorators'
import {Context, LoggerInstance, ServiceBroker, ServiceSchema} from 'moleculer';
import {Connection, createConnection} from 'typeorm';
import {hostname} from 'os';

@Service({
    name: 'TEst',
})
class TestService {
    public broker: ServiceBroker;
    public logger: LoggerInstance;
    public schema: ServiceSchema;
    public connection: Connection;

    @Action({
        cache: true,
        params: {
            test: { type: 'string', optional: true }
        }
    })
    public testAction(ctx: Context): {[key: string]: any} {
        this.logger.info(ctx.params);
        return ctx.params;
    }

    // @ts-ignore
    public async service(): void {
        this.broker.cacher.clean();

        this.connection = await createConnection({
            name: 'default',
            type: 'mongodb',
            url: 'localhost',
            synchronize: false,
            entities: [__dirname + '/entity/{*.ts,*.js}'],
            logging: true,
        });
    }
}


const broker: ServiceBroker = new ServiceBroker({
    namespace: 'core',
    nodeID: hostname().toLowerCase() + "-" + process.pid,
    logger: true,
    logLevel: 'info',
});

broker.createService(TestService);

broker.start()
    .then(() => {
        // broker.repl();
    });

**Comment by damiandabrowski** [comment]
And simple entity

guest.ts

`
import {Entity, ObjectID, ObjectIdColumn, Column, Index, BaseEntity} from 'typeorm';

@Entity()
@Index(['first_name', 'last_name'])
export class Guest extends BaseEntity{
    @ObjectIdColumn()
    public guest_id: ObjectID;

    @Column({type: 'text'})
    public first_name: string;

    @Column({type: 'text', nullable: true})
    public last_name: string;
}

`

**Comment by damiandabrowski** [comment]
**/typeorm-decorators/node_modules/reflect-metadata/Reflect.js:544
                        throw new TypeError();
                        ^

TypeError

**Comment by damiandabrowski** [comment]
package depts

`"devDependencies": { 
    "@types/node": "^10.3.0",
    "conventional-changelog-cli": "^2.0.0",
    "moleculer-repl": "^0.4.0",
    "rimraf": "^2.6.2",
    "tslib": "^1.9.2",
    "tslint": "^5.10.0",
    "tslint-microsoft-contrib": "^5.0.3",
    "typescript": "^2.9.1"
  },
  "dependencies": {
    "moleculer": "^0.12.5",
    "moleculer-decorators": "^1.0.14",
    "typeorm": "^0.2.7",
    "nats": "^0.8.10"
  }

`

**Comment by damiandabrowski** [comment]
"build": "tsc -p tsconfig.release.json",

------------------------------

{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": false,
    "declaration": false,
    "noImplicitAny": false,
    "rootDir": "./src",
    "outDir": "build",
    "allowSyntheticDefaultImports": true,
    "removeComments": true,
    "jsx": "react",
    "allowJs": true,
    "importHelpers": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "include": [
    "src/**/*",
    "declarations/**/*"
  ],
  "exclude": [
    "src/**/__mocks__"
  ]
}

**Comment by ColonelBundy** [comment]
This has, unfortunately, nothing to do with moleculer-decorators.

**Comment by leomongeg** [comment]
Hey @damiandabrowski ,

Do you solve your issue? I'm experimenting the same issue when I tried to implement TypeDi.

Regards,
Leonardo Monge García.

**Comment by ColonelBundy** [comment]
@leomongeg I was unable to reproduce, could you also provide some sample code?

**Comment by pewh** [comment]
would you mind to reopen this ticket?

this is the sample repo that produce same error https://github.com/pewh/moleculer-db-adapter-typeorm-example. I clone from https://github.com/dkuida/moleculer-db-adapter-typeorm and add moleculer-decorators.

To run, use: `npm run build && npm run dev`

**Comment by leomongeg** [comment]
Hey, would be great if you can re-open this ticket!

Let me too prepare a repo that I have with the same issue.

Regards, 
Leonardo Monge García

**Comment by ColonelBundy** [comment]
I can't seem to replicate this issue. PR's are welcome if you can locate and fix it

**Comment by darky** [comment]
Unfortunately, this issue affected me too.
Revert to simple https://moleculer.services/docs/0.13/services.html#ES6-classes ES6 classes case.
`moleculer-decorators` totally blocks me :(
