### ISSUE TITLE
Typescript methods declaration

### ISSUE THREAD

**Issue by RuBAN-GT** [ColonelBundy/moleculer-decorators#5]
Good day, everyone! Firstly, thank you for your package!
I have a small question: how I can define decorators methods and properties for my class?

For example:

```typescript
import { Action, Service } from 'moleculer-decorators'

@Service({ name: 'users' })
export class UsersService {
  @Action()
  sample() {
    this.logger.info('What?')
  }
}
```

The TS compiler doesn't know about `logger` property, I can define it manually, but... Can I have beauty solution for all properties and service methods? And also how I can define mixin implementation of some methods?

Thank you!

**Comment by ColonelBundy** [comment]
For now you can simply do this:

```
import { Action, Service } from 'moleculer-decorators'
import moleculer = require('moleculer');

@Service({ name: 'users' })
export class UsersService {
  private logger: moleculer.LoggerInstance;

  @Action()
  sample() {
    this.logger.info('What?')
  }
}
```

The new typescript mixin's will solve this. But use this for now until I get around implementing it with mixins.
