### ISSUE TITLE
ActionOptions Typescript Typedef missing some options?

### ISSUE THREAD

**Issue by mashaalmemon** [ColonelBundy/moleculer-decorators#6]
Hi There,

I'm trying to use decorators with Typescript. In your README.md example, we can set cache value per action:

```
  // With options
  // No need for "handler:{}" here
  @Action({
    cache: false,
    params: {
      a: "number",
      b: "number"
    }
  })
```

But when defining an `@Action` the type checking complains as it isn't defined:
```
export interface ActionOptions extends Partial<Action> {
  name?: string,
  handler?: ActionHandler<any>, // Not really used
  skipHandler?: boolean
}
```

It appears, "cache" should be defined in the Typescript typedef? Or perhaps I'm missing something key?

**Comment by ColonelBundy** [comment]
Cache does exist since it extends the moleculer action interface.
